metadata:
  name: "matplotlib"
  version: "3.10.8"
  download_version: "3.10.8"

build:
  system_dependencies:
    - "freetype"
    - "qhull"
    - "ninja"
  env:
    CXXFLAGS: "-Wno-c++11-narrowing"
  patches:
    - "patches/0001-use-system-dependencies.patch"
    - "patches/0002-fix-shebang.patch"
